title: Cats
modelClass: Arteriaweb\Shop\Models\Cat
list: $/arteriaweb/shop/models/cat/columns.yaml
recordUrl: 'arteriaweb/shop/cats/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
